server: ../daytimetcpsrv1.c ../../../common/libunp.a ../../../common/config.h
	gcc ../daytimetcpsrv1.c -I../../../common -L../../../common -lunp -o ./time_server1.out -Wall -Wpedantic
clean: time_server1.out
	rm time_server1.out
all: client 
